name: MPRPG
main: com.minepile.mprpg.MPRPG
version: 0.1
description: MinePile RPG
author: unenergizer
website: http://www.minepile.com/
commands:
   cc:
      description: Used to change players chat channel.
   chat:
      description: Used to change players chat channel.
   chatchanel:
      description: Used to change players chat channel.
   ch:
      description: Used to change players chat channel.
   msg:
      description: Used to send other players private messages.
   message:
      description: Used to send other players private messages.
   pm:
      description: Used to send other players private messages.
   tell:
      description: Used to send other players private messages.
   r:
      description: Used to send other players private messages.
   lag:
      description: Get the server TPS and lag percent.
  