name: MPRPG
main: com.minepile.mprpg.MPRPG
version: 0.1
description: MinePile RPG
author: unenergizer
website: http://www.minepile.com/
commands:
   cc:
      description: Used to change players chat channel.
   chat:
      description: Used to change players chat channel.
   chatchanel:
      description: Used to change players chat channel.
   ch:
      description: Used to change players chat channel.